# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js

# Make sure that branch and PR triggers are enabled in Travis CI settings on the web UI, and then
# it will run whenever a PR is opened and whenever a new commit is merged into one of these branches
branches:
  only:
    - master

git:
  depth: 2

# Node version
node_js: '12.14.0'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > "$HOME/.npmrc"
  - npm install -g yarn@1.22.4
  - python -m pip install --upgrade pip --user
  - pip install pre-commit --user
  - export PATH=$PATH:$HOME/.local/bin

# Install top level dependencies
install:
  - yarn

# the following line is needed to enable the TravisCI build conditions
conditions: v1

# Run these commands
jobs:
  include:
    # ##### #
    # Tests #
    # ##### #

    # Run pre-commit hooks on all files
    - stage: test
      name: Pre-Commits
      script:
        - pre-commit run --all-files

    # Run tests
    - stage: test
      name: Tests
      script: npm run test

    # ###### #
    # Deploy #
    # ###### #

    # Deploy to npm
    - stage: deploy
      script: skip
      deploy:
        - provider: npm
          email: '$NPM_EMAIL'
          api_key: '$NPM_TOKEN'
          skip_cleanup: true
          on:
            branch: master

cache:
  directories:
    # Cache pip activities to speed up pre-commit installation
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -f $HOME/.cache/pre-commit/pre-commit.log
  - rm -f $HOME/.npm/anonymous-cli-metrics.json

addons:
  apt:
    packages:
      - 'python'
